name: arb_tsv
description: This package provides conversion between arb files and tsv files and merging arb files for easy internationalization.
version: 2.0.0
homepage: https://github.com/flutterstudygn/arb_tsv

environment:
  sdk: '>=2.12.0 <3.0.0'
  
dependencies:
  args: ^2.1.1
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.16.8
