name: arb_tsv
description: This package provides conversion between arb files and tsv files and merging arb files for easy internationalization.
version: 1.0.0
homepage: https://github.com/flutterstudygn/arb_tsv

environment:
  sdk: '>=2.8.1 <3.0.0'
  
dependencies:
  args: ^1.6.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
